// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otkvjhgvounrfblrwqtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a3ZqaGd2b3VucmZibHJ3cXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzY1NzcsImV4cCI6MjA2NjUxMjU3N30.qUUZiLaiXVIvg--t9CT60Hmxbl9W1yX-s05G0bIvPiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);